### PR TITLE
Feat movies reverse proxy

### PR DESCRIPTION
**Pull request by gabriel-okteto**

### CODE REVIEW

**Review by pchico83 — APPROVED** [review]
Great!
Could you apply the same changes to https://github.com/okteto/movies-with-helm?

**Comment by rberrelleza** [comment]
Do we need to update the getting started guides with this change? (Screenshots, descriptions, etc...)

**Comment by rberrelleza** [comment]
Do we need to update the getting started guide to consider this change? (Screenshots, description, etc...)

**Comment by rberrelleza** [comment]
Also,how is this going to work for the compose version? I think we have same the same issue there, right? @gabriel-okteto @pchico83

**Comment by gabriel-okteto** [comment]
the docs/getting-started image showing the two endpoint could be updated to show that there are three endpoint deployed `api/movies` && 'api/watching' vs previous 'api' && frontend

**Comment by rberrelleza** [comment]
Closing since this has been abandoned

**Pull request closed without merging**
